import { ServiceCategory } from "@/types/service";

export const servicesData: ServiceCategory[] = [
  {
    id: "software-development",
    title: "Software Development",
    icon: "🧩",
    description: "End-to-end custom software solutions built for performance, scalability, and user experience",
    subServices: [
      { title: "Web Applications", icon: "🌐" },
      { title: "Android Apps", icon: "📱" },
      { title: "iOS Apps", icon: "🍎" },
      { title: "Native / Hybrid Apps", icon: "⚡" },
      { title: "WebApps / PWAs", icon: "💻" },
      { title: "Desktop Applications", icon: "🖥️" },
    ],
    techStack: [
      { name: "React", category: "Frontend" },
      { name: "Next.js", category: "Frontend" },
      { name: "Angular", category: "Frontend" },
      { name: "Vue", category: "Frontend" },
      { name: "Node.js", category: "Backend" },
      { name: ".NET", category: "Backend" },
      { name: "Python", category: "Backend" },
      { name: "Java", category: "Backend" },
      { name: "Flutter", category: "Mobile" },
      { name: "React Native", category: "Mobile" },
      { name: "Swift", category: "Mobile" },
      { name: "Kotlin", category: "Mobile" },
      { name: "Electron", category: "Desktop" },
      { name: "Tauri", category: "Desktop" },
      { name: "Docker", category: "DevOps" },
      { name: "CI/CD", category: "DevOps" },
      { name: "AWS", category: "DevOps" },
    ],
  },
  {
    id: "cloud-devops",
    title: "Cloud Engineering & DevOps",
    icon: "☁️",
    description: "Scalable cloud infrastructure and automated CI/CD pipelines for modern enterprises",
    subServices: [
      { title: "Cloud Architecture (AWS / Azure / GCP)", icon: "🏗️" },
      { title: "Cloud Migration", icon: "🚀" },
      { title: "CI/CD Automation", icon: "⚙️" },
      { title: "Kubernetes Management", icon: "☸️" },
      { title: "Infrastructure as Code (Terraform)", icon: "📋" },
      { title: "Serverless Engineering", icon: "⚡" },
    ],
    techStack: [
      { name: "AWS", category: "Cloud" },
      { name: "Azure", category: "Cloud" },
      { name: "GCP", category: "Cloud" },
      { name: "Kubernetes", category: "Container" },
      { name: "Docker", category: "Container" },
      { name: "Terraform", category: "IaC" },
      { name: "Ansible", category: "IaC" },
      { name: "GitHub Actions", category: "CI/CD" },
      { name: "GitLab CI", category: "CI/CD" },
      { name: "Jenkins", category: "CI/CD" },
    ],
  },
  {
    id: "automation",
    title: "Automation & Digital Operations",
    icon: "⚙️",
    description: "Intelligent automation solutions to streamline business processes and reduce manual overhead",
    subServices: [
      { title: "Intelligent Workflow Automation", icon: "🤖" },
      { title: "AI & RPA Automation", icon: "🧠" },
      { title: "Document & Data Automation", icon: "📄" },
      { title: "Business Process Automation", icon: "🔄" },
      { title: "System Integrations & APIs", icon: "🔌" },
    ],
    techStack: [
      { name: "Python Automation", category: "Language" },
      { name: "UiPath", category: "RPA" },
      { name: "Selenium", category: "Testing" },
      { name: "Zapier", category: "Integration" },
      { name: "Make", category: "Integration" },
      { name: "Airflow", category: "Workflow" },
      { name: "Generative AI", category: "AI" },
    ],
  },
  {
    id: "cybersecurity",
    title: "Cyber Security Solutions",
    icon: "🔐",
    description: "Comprehensive security services protecting your digital assets from modern threats",
    subServices: [
      {
        title: "MDR – 24/7 Threat Detection & Response",
        description: "Managed detection and response with round-the-clock monitoring and rapid incident response",
        icon: "🛡️",
      },
      {
        title: "CSPM – Cloud Security & Compliance",
        description: "Cloud security posture management ensuring compliance and best practices",
        icon: "☁️",
      },
      {
        title: "Email Security & DLP",
        description: "Advanced email protection and data loss prevention strategies",
        icon: "📧",
      },
      {
        title: "SOAR & Security Automation",
        description: "Security orchestration, automation, and response for streamlined security operations",
        icon: "⚙️",
      },
      {
        title: "Identity & Access Governance (IGA)",
        description: "Comprehensive identity management and access control solutions",
        icon: "👤",
      },
      {
        title: "Vulnerability & Patch Management",
        description: "Proactive vulnerability assessment and systematic patch deployment",
        icon: "🔍",
      },
      {
        title: "Brand & Dark Web Monitoring",
        description: "Continuous monitoring of brand reputation and dark web threats",
        icon: "🌐",
      },
    ],
    techStack: [
      { name: "CrowdStrike", category: "Endpoint" },
      { name: "SentinelOne", category: "Endpoint" },
      { name: "Microsoft Defender", category: "Endpoint" },
      { name: "Splunk", category: "SIEM" },
      { name: "ELK", category: "SIEM" },
      { name: "Wazuh", category: "SIEM" },
      { name: "Sentinel", category: "SIEM" },
      { name: "Okta", category: "IAM" },
      { name: "Azure AD", category: "IAM" },
      { name: "AWS IAM", category: "IAM" },
      { name: "Qualys", category: "Vulnerability" },
      { name: "Nessus", category: "Vulnerability" },
      { name: "Rapid7", category: "Vulnerability" },
    ],
  },
  {
    id: "third-party-developers",
    title: "Third Party Developers",
    icon: "👥",
    description: "Expert third-party development teams ready to integrate seamlessly into your projects and accelerate delivery",
    subServices: [
      {
        title: "Dedicated Development Teams",
        description: "Full-time dedicated developers integrated into your workflow",
        icon: "👨‍💻",
      },
      {
        title: "Offshore Development Services",
        description: "Cost-effective offshore development teams with proven track records",
        icon: "🌍",
      },
      {
        title: "Nearshore Development",
        description: "Time-zone aligned development teams for better collaboration",
        icon: "⏰",
      },
      {
        title: "Outsourced Development Projects",
        description: "Complete project outsourcing with end-to-end delivery",
        icon: "📦",
      },
      {
        title: "Technical Consulting & Advisory",
        description: "Expert technical guidance and architecture consulting",
        icon: "💡",
      },
      {
        title: "Code Review & Quality Assurance",
        description: "Professional code reviews and quality assessments",
        icon: "✅",
      },
      {
        title: "Legacy System Modernization",
        description: "Modernizing and refactoring legacy applications",
        icon: "🔄",
      },
      {
        title: "Technical Support & Maintenance",
        description: "Ongoing technical support and maintenance services",
        icon: "🔧",
      },
    ],
    techStack: [
      { name: "Full-Stack Development", category: "Expertise" },
      { name: "Agile Methodologies", category: "Methodology" },
      { name: "Scrum", category: "Methodology" },
      { name: "DevOps Integration", category: "Integration" },
      { name: "Git/GitHub", category: "Version Control" },
      { name: "Jira", category: "Project Management" },
      { name: "Confluence", category: "Collaboration" },
      { name: "Slack/Teams", category: "Communication" },
      { name: "Code Quality Tools", category: "Quality" },
      { name: "Testing Frameworks", category: "Quality" },
    ],
  },
  {
    id: "support-and-service",
    title: "Support and Service",
    icon: "🛟",
    description: "Comprehensive IT support and service solutions ensuring optimal performance and reliability of your systems",
    subServices: [
      {
        title: "24/7 Technical Support",
        description: "Round-the-clock technical support with guaranteed response times",
        icon: "🚨",
      },
      {
        title: "Help Desk Services",
        description: "Centralized help desk for all IT-related issues and requests",
        icon: "🎫",
      },
      {
        title: "Remote Support & Troubleshooting",
        description: "Remote access support for quick issue resolution",
        icon: "💻",
      },
      {
        title: "System Monitoring & Maintenance",
        description: "Proactive monitoring and scheduled maintenance services",
        icon: "📊",
      },
      {
        title: "Performance Optimization",
        description: "System performance tuning and optimization services",
        icon: "⚡",
      },
      {
        title: "Backup & Disaster Recovery",
        description: "Comprehensive backup solutions and disaster recovery planning",
        icon: "💾",
      },
      {
        title: "Software Updates & Patch Management",
        description: "Automated and manual software update services",
        icon: "🔄",
      },
      {
        title: "User Training & Documentation",
        description: "End-user training and comprehensive system documentation",
        icon: "📚",
      },
      {
        title: "Service Level Agreements (SLA)",
        description: "Guaranteed service levels with defined response times",
        icon: "📋",
      },
      {
        title: "Managed IT Services",
        description: "Complete IT infrastructure management and support",
        icon: "🏢",
      },
    ],
    techStack: [
      { name: "ServiceNow", category: "Service Management" },
      { name: "Zendesk", category: "Ticketing" },
      { name: "Jira Service Management", category: "Ticketing" },
      { name: "Nagios", category: "Monitoring" },
      { name: "Zabbix", category: "Monitoring" },
      { name: "Datadog", category: "Monitoring" },
      { name: "New Relic", category: "Monitoring" },
      { name: "PagerDuty", category: "Incident Management" },
      { name: "Ansible", category: "Automation" },
      { name: "Puppet", category: "Configuration Management" },
      { name: "Chef", category: "Configuration Management" },
      { name: "Backup Solutions", category: "Data Protection" },
    ],
  },
];

